version: "3.1"
services:
  mongo:
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: app
    ports:
    - 27017:27017

  gameapi:
    image: ebanina
    command: [
      "./application",
      "-Dquarkus.http.host=0.0.0.0",
      "-Dquarkus.mongodb.connection-string=mongodb://root:example@mongo:27017",
      "-Dquarkus.mongodb.database=app"
    ]
    ports:
    - 8080:8080
