version: "3.4"
services:
  mongo:
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: app
    volumes:
# todo - "${PWD}/db/init.js:/docker-entrypoint-initdb.d/init.mongo.js:ro"
      - "mongo-data:/data/db"
    ports:
      - 27017:27017
    networks:
      - backend

  gameapi:
    image: zhenik/ocn-backend:1.01
    command: [
      "./application",
      "-Dquarkus.http.host=0.0.0.0",
      "-Dquarkus.mongodb.connection-string=mongodb://root:example@mongo:27017",
      "-Dquarkus.mongodb.database=app",
      "-Dquarkus.http.cors=true",
      "-Dquarkus.http.cors.methods=GET,PUT,POST",
      "-Dquarkus.http.proxy-address-forwarding=true",
      "-Dquarkus.http.allow-forwarded=true",
      "-Dquarkus.http.cors.access-control-max-age=24H",
      "-Dquarkus.http.cors.origins=http://localhost:3000,http://localhost,http://54.171.115.231:3000,http://54.171.115.231"
    ]
    ports:
      - 8080:8080
    networks:
      - backend
    depends_on:
      - mongo

volumes:
  mongo-data:
    name: "mongo-data"
networks:
  backend:
  frontend:
